apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-applicationset
  namespace: argocd
spec:
  generators:
  - list:
      elements:
        - app-name: my-app-1
          namespace: dev
        - app-name: my-app-2
          namespace: dev
  template:
    metadata:
      name: '{{app-name}}-dev'
    spec:
      project: dev
      source:
        repoURL: https://github.com/cyberdine-skynet/skynet-k8s-manifests.git
        path: projects/dev/apps/{{app-name}}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
