apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docusaurus-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cyberdine-skynet/skynet-k8s-manifests
    targetRevision: HEAD
    path: apps/skynet-app/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: workload-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
