apiVersion: apps/v1
kind: Deployment
metadata:
  name: docusaurus
  namespace: docusaurus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docusaurus
  template:
    metadata:
      labels:
        app: docusaurus
    spec:
      containers:
      - name: docusaurus
        image: teknoseeker/docusaurus:latest
        ports:
        - containerPort: 8687
