apiVersion: v1
kind: Service
metadata:
  name: docusaurus
  namespace: docusaurus
spec:
  selector:
    app: docusaurus
  ports:
  - protocol: TCP
    port: 8687
    targetPort: 8687
    nodePort: 30687
  type: NodePort
