apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      initContainers:
      - name: init-loki-dirs
        image: busybox
        command: [ "sh", "-c", "mkdir -p /loki/index /loki/cache /loki/chunks /loki/compactor /loki/wal" ]
        volumeMounts:
        - name: loki-pvc
          mountPath: /loki
      - name: fix-perms
        image: busybox
        command: [ "sh", "-c", "chown -R 10001:10001 /loki" ]
        volumeMounts:
        - name: loki-pvc
          mountPath: /loki
      containers:
      - name: loki
        image: grafana/loki:2.9.3
        args:
        - -config.file=/etc/loki/loki-config.yaml
        ports:
        - containerPort: 3100
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          runAsUser: 10001
        volumeMounts:
        - name: loki-pvc
          mountPath: /loki
        - name: loki-config
          mountPath: /etc/loki/loki-config.yaml
          subPath: loki-config.yaml
      volumes:
      - name: loki-pvc
        persistentVolumeClaim:
          claimName: loki-pvc
      - name: loki-config
        configMap:
          name: loki-config
