apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      containers:
      - name: fluent-bit
        image: fluent/fluent-bit:2.2.2
        args:
        - -c
        - /fluent-bit/etc/fluent-bit.conf
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: config
          mountPath: /fluent-bit/etc
      volumes:
      - name: config
        configMap:
          name: fluent-bit-config
