apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: traefik
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: traefik
rules:
- apiGroups: [ "" ]
  resources: [ "services", "endpoints", "secrets", "pods", "nodes" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "extensions", "networking.k8s.io" ]
  resources: [ "ingresses", "ingressclasses" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "traefik.containo.us" ]
  resources: [ "middlewares", "ingressroutes", "ingressroutetcps", "ingressrouteudps", "tlsoptions", "tlsstores", "traefikservices" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "traefik.io" ]
  resources: [ "middlewares", "ingressroutes", "ingressroutetcps", "ingressrouteudps", "tlsoptions", "tlsstores", "traefikservices", "serverstransports" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik
subjects:
- kind: ServiceAccount
  name: traefik
  namespace: traefik
